spring.application.name=DailyMotionMiner
server.port=8082

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.error.include-message=always
server.error.include-binding-errors=always

# VideoMiner service URL
videominer.url=http://localhost:8080
