spring.application.name=PeerTubeMiner
server.port=8081

# VideoMiner service URL (El Almacen Central)
videominer.url=http://localhost:8080

# Swagger para el Notable
springdoc.swagger-ui.path=/swagger-ui.html
peertube.api.url=https://peertube.tv